/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/********************** ĐỊNH NGHĨA ĐỊA CHỈ THANH GHI ***************/

#define RCC_BASE 		0x40023800UL
#define RCC_CFGR		(RCC_BASE + 0x08)	// clock configuration register
#define RCC_AHB1ENR		(RCC_BASE + 0x30)	// AHB1 peripheral clock enable register

#define GPIOA_BASE		0x40020000UL
#define GPIOA_MODER		(GPIOA_BASE + 0x00)	// GPIOA port mode register
#define GPIOA_OSPEEDR	(GPIOA_BASE + 0x08)	// GPIOA output speed register
#define GPIOA_AFRH		(GPIOA_BASE +  0x24)// GPIOA alternate function high register

/********************** CẤU HÌNH PRESCALER MCO1 ********************/
#define MCO1_PRESCALER	(0x6 << 24)			// Devision by 4 (110 << 24)

/********************** HÀM CẤU HÌNH CLOCK *****************************/
void config_Clock(void)
{
	// 🔴 Bước 1: Bật clock cho GPIOA (AHB1ENR bit 0)
	*((volatile uint32_t *) RCC_AHB1ENR) |= (1 << 0);
	// 🔴 Bước 2: Clear bit cấu hình MCO1 cũ (bit 21-22)
	*((volatile uint32_t *)RCC_CFGR) &= ~(0x3 << 21);
	// 🔴 Bước 3: Set HSI làm nguồn cho MCO1 (00 << 21 - mặc định)
//	*((volatile uint32_t *)RCC_CFGR) |= (0x0 << 21);
	// 🔴 Bước 4: Clear prescaler cũ (bit 24-26)
	*((volatile uint32_t *)RCC_CFGR) &= ~(0x7 << 24);
	// 🔴 Bước 5: Áp dụng prescaler mới (chia 4)
	*((volatile uint32_t *)RCC_CFGR) |= MCO1_PRESCALER;
}

/********************** HÀM CẤU HÌNH GPIOA ************************/
void config_gpio(void)
{
	// Bước 1: set mode
	*((volatile uint32_t *) GPIOA_MODER) &= ~(0x3 << 16);
	*((volatile uint32_t *) GPIOA_MODER) |= (0x2 << 16);
	// Bước 2: set speed for PA8
	*((volatile uint32_t *) GPIOA_OSPEEDR) &= ~(0x3 << 16);
	*((volatile uint32_t *) GPIOA_OSPEEDR) |= (0x2 << 16);
	// Bước 3: set AF0 for pin PA8
	*((volatile uint32_t *) GPIOA_AFRH) &= ~(0x3 << 16);
//	*((volatile uint32_t *) GPIOA_AFRH) |= (0x0 << 16);

}

int main(void)
{
	config_Clock();
	config_gpio();
    /* Loop forever */
	for(;;);
}
